### ISSUE TITLE
Updated Codebase

### ISSUE THREAD

**Issue by allincmu** [rkrabek/ballroom-ycn-verifier#3]
Hello, 

I came across your project this afternoon and I updated the codebase so it works again. Do you want my updates? I can open a pull request.

**Comment by rkrabek** [comment]
Hey that would be great! Also I'd be happy to make you a contributor on this repo if that would make the workflow easier if there are any other changes you think you might want to make in the future.

**Comment by allincmu** [comment]
Sure! feel free to make me a contributor. For this update, I just forked the repo, but as you said, it might be useful to be a contributor in the future.  I think the next thing I want to do is multithread `comp_res_scraper.py`. Other than that, I'm not sure I have any ideas for changes at the moment.

**Comment by rkrabek** [comment]
Merged in https://github.com/rkrabek/ballroom-ycn-verifier/commit/0adfbd895af245da38b085c02919c4fbcee04712
